// Per-company accent colours as space-separated RGB triplets (for Tailwind opacity support)
export const DEFAULT_COMPANIES = [
  {
    id: 'BCB',
    name: 'Bond Cleaners in Brisbane',
    prefix: 'BCB',
    phone: '+61 468 040 044',
    email: 'info@bondcleanerinbrisbane.com.au',
    website: 'www.bondcleanerinbrisbane.com.au',
    address: '1131 Mount Cotton Rd, Burbank QLD 4123',
    accentRgb: '30 136 229',
    accentDarkRgb: '21 101 192',
    bankDetails: 'Account Name: Bond Cleaners in Brisbane\nBSB: TBC\nAccount No: TBC',
    invoiceTemplate: 'minimal',
  },
  {
    id: 'BCA',
    name: 'Bond Cleaners Australia',
    prefix: 'BCA',
    phone: '+61 468 080 800',
    email: 'team@bondcleanersaustralia.com.au',
    website: 'www.bondcleanersaustralia.com.au',
    address: '1131 Mount Cotton Rd, Burbank QLD 4123',
    accentRgb: '249 154 31',
    accentDarkRgb: '220 130 10',
    bankDetails: 'Account Name: Bond Cleaners Australia\nBSB: TBC\nAccount No: TBC',
    invoiceTemplate: 'corporate',
  },
  {
    id: 'SBC',
    name: 'Shine Bond Clean',
    prefix: 'SBC',
    phone: '+61 468 000 202',
    email: 'info@shinebondclean.com.au',
    website: 'www.shinebondclean.com.au',
    address: '1131 Mount Cotton Rd, Burbank QLD 4123',
    accentRgb: '34 197 94',
    accentDarkRgb: '22 163 74',
    bankDetails: 'Account Name: Shine Bond Clean\nBSB: TBC\nAccount No: TBC',
    invoiceTemplate: 'soft',
  },
  {
    id: 'SSS',
    name: 'SSS OZ Cleaning',
    prefix: 'SSS',
    phone: '+61 485 030 303',
    email: 'SSSOZCLEANING@outlook.com',
    website: 'www.SssOzCleaning.com.au',
    address: '20 Borman St, Slacks Creek QLD 4127',
    accentRgb: '139 92 246',
    accentDarkRgb: '124 58 237',
    bankDetails: 'Account Name: SSS OZ Cleaning\nBSB: TBC\nAccount No: TBC',
    invoiceTemplate: 'minimal',
  },
  {
    id: 'MBC',
    name: 'Mama Bond Cleaners',
    prefix: 'MBC',
    phone: '+61 468 156 176',
    email: 'Mamabondcleaning@outlook.com',
    website: 'www.mamabondcleaning.com.au',
    address: 'TBC',
    accentRgb: '20 184 166',
    accentDarkRgb: '13 148 136',
    bankDetails: 'Account Name: Mama Bond Cleaners\nBSB: TBC\nAccount No: TBC',
    invoiceTemplate: 'corporate',
  },
];

export const DEFAULT_LINE_ITEMS = [
  { description: 'Cleaning Service', qty: 1, unitPrice: 500 },
  { description: 'Carpet Cleaning', qty: 1, unitPrice: 35 },
  { description: 'Pest or Flea Treatment', qty: 1, unitPrice: 160 },
  { description: 'Any Extra Work', qty: 1, unitPrice: 0 },
];
